### PR TITLE
Fix #805 - Check property exists before using it

### LINKED ISSUE #805: bug: Foundry deploy causes bug due to ast property being undefined
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Which method was used to setup Scaffold-ETH 2 ?

npx create-eth@latest

### Current Behavior

If you create a new scaffold-eth2 project using `foundry`, whilst deploying (without touching any of the code apart from `packages/foundry/.env` file to add `DEPLOYER_PRIVATE_KEY`), you will get an error at the end of the deploy, like this

```
TypeError: Cannot read properties of undefined (reading 'nodes')
    at getInheritedFromContracts (/Users/.../packages/foundry/script/generateTsAbis.js:40:38)
    at getInheritedFunctions (/Users/.../packages/foundry/script/generateTsAbis.js:53:34)
    at /Users/.../packages/foundry/script/generateTsAbis.js:109:29
    at Array.forEach (<anonymous>)
    at /Users/.../packages/foundry/script/generateTsAbis.js:101:24
    at Array.forEach (<anonymous>)
    at main (/Users/.../packages/foundry/script/generateTsAbis.js:93:10)
    at Object.<anonymous> (/Users/.../packages/foundry/script/generateTsAbis.js:143:3)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
```

### Expected Behavior

No error about `ast` property being undefined

### Steps To Reproduce

* `npx create-eth@latest`
* choose foundry
* run `yarn chain`
* run `yarn start`
* run `yarn deploy`

### Anything else?

Suggest the following edit to `packages/foundry/script/generateTsAbis.js`

```
function getInheritedFromContracts(artifact) {
  let inheritedFromContracts = [];
  if('ast' in artifact) {
    for (const astNode of artifact.ast.nodes) {
      if (astNode.nodeType == "ContractDefinition") {
        if (astNode.baseContracts.length > 0) {
          inheritedFromContracts = astNode.baseContracts.map(
            ({ baseName }) => baseName.name
          );
        }
      }
    }
  }
  return inheritedFromContracts;
}
```

### PR DESCRIPTION
**Pull request by dragonsisdumb**
## Description

Fixes: https://github.com/scaffold-eth/scaffold-eth-2/issues/805

Sometimes (reproducible by me but not @technophile-04) the `yarn deploy` would error complaining about using an undefined property. This fixes that.

## Additional Information

- [x] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #805_

Your ENS/address:

### CODE REVIEW

File: templates/extensions/foundry/packages/foundry/script/generateTsAbis.js [hunk 1]
```diff
@@ -36,12 +36,14 @@ function getArtifactOfContract(contractName) {
 
 function getInheritedFromContracts(artifact) {
   let inheritedFromContracts = [];
-  for (const astNode of artifact.ast.nodes) {
-    if (astNode.nodeType == "ContractDefinition") {
-      if (astNode.baseContracts.length > 0) {
-        inheritedFromContracts = astNode.baseContracts.map(
-          ({ baseName }) => baseName.name
-        );
+  if('ast' in artifact) {
```
Comment (rin-st) [inline templates/extensions/foundry/packages/foundry/script/generateTsAbis.js:39]: Thanks for your pr!

`'ast' in artifact` is true even when `ast` is undefined.

image

so it should fail even in your case

Better to use 
`if (artifact?.ast) {`

Comment (technophile-04) [reply templates/extensions/foundry/packages/foundry/script/generateTsAbis.js:39]: @dragonsisdumb could you please update it ?

**Review by technophile-04 — APPROVED** [review]
