### PR TITLE
cli: skip prettier formatting if install dependency is skipped

### LINKED ISSUE #783: bug: Cli: Failed to create directory if skip installing dependencies
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Which method was used to setup Scaffold-ETH 2 ?

git clone

### Current Behavior

```
yarn cli    

 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 | Create Scaffold-ETH 2 app |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+

? Your project name: kjkk
? What solidity framework do you want to use? hardhat
? Install packages? No


  ✔ 📁 Create project directory /Users/liana/Documents/se-2/kjkk
  ✔ 🚀 Creating a new Scaffold-ETH 2 app in kjkk
  ↓ 📦 Installing dependencies with yarn, this could take a while [skipped]
    → Manually skipped
  ✖ 🪄 Formatting files with prettier
    → Failed to create directory
    📡 Initializing Git repository 
ERROR Error occurred Error: Failed to create directory
    at prettierFormat ...
```

### Expected Behavior

Directory is created

### Steps To Reproduce

Skip installing deps for both hh/foundry

### Anything else?

It tries to run prettier without installing prettier

### PR DESCRIPTION
**Pull request by technophile-04**
## Description

Fixes #783, This is kind of short-term solution for now since if you skip install dependency it will not install prettier, which in turn will not format files. 

We added a prettier formatting file task because we get a prettier warning : 

Screenshot 2024-03-23 at 12 20 22 AM

Also checkout #750 for more context 🙌

### CODE REVIEW

File: src/tasks/prettier-format.ts [hunk 1]
```diff
@@ -1,5 +1,6 @@
 import { execa } from "execa";
 
+// TODO: Instead of using execa, use prettier pacakge from cli to format targetDir
```
Comment (rin-st) [inline src/tasks/prettier-format.ts:3]: package*

**Review by rin-st — APPROVED** [review]
lgtm!

File: src/tasks/prettier-format.ts (hunk 1 above)
Comment (technophile-04) [reply src/tasks/prettier-format.ts]: Ohh tysm !! lol for some reason even github copilot has started making spell mistake like me :(
