### PR TITLE
Fix/auto connect

### LINKED ISSUE #391: bug: autoConnect is not working
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

It seems that autoConnect does not works properly, even thought you have `autoConnect: true` in `scaffold.config`

### Expected Behavior

It should autoConnect if you have it enabled

### Steps To Reproduce

1. Change `targetNetwork`to `chains.sepolia`
2. Run frontend and connect wallet 
3. Refresh the page, it will tell you to again connect the wallet

### Anything else?

It seems that this was caused due to #356, if you check out to its parent commit there it works fine

### PR DESCRIPTION
**Pull request by rin-st**
## Description
Fixes auto connect and hydration error. Removes `useAutoConnect` hook since auto connect now works without a hook. Please lmk if it is still needed

## Additional Information

- [x] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

Closes #391 

Your ENS/address: 0xrinat

### CODE REVIEW

File: packages/nextjs/components/scaffold-eth/Faucet.tsx [hunk 1]
```diff
@@ -74,7 +77,7 @@ export const Faucet = () => {
   };
 
   // Render only on local chain
-  if (!ConnectedChain || ConnectedChain.id !== hardhat.id) {
+  if (ConnectedChain?.id !== hardhat.id || !isMounted()) {
```
Comment (sverps) [inline packages/nextjs/components/scaffold-eth/Faucet.tsx:80]: Don't think we need `isMounted` here. This line is only evaluated during rendering of this component, at which stage `isMounted()` should always return true. When the component isn't mounted, this code will not be executed.

(Checking `isMounted` is more for async stuff, for example when waiting for a response from an API, it's possible the user navigates away and the component that made the request gets unmounted.)

File: packages/nextjs/components/scaffold-eth/FaucetButton.tsx [hunk 2]
```diff
@@ -40,7 +44,7 @@ export const FaucetButton = () => {
   };
 
   // Render only on local chain
-  if (!ConnectedChain || ConnectedChain.id !== hardhat.id) {
+  if (ConnectedChain?.id !== hardhat.id || !isMounted()) {
```
Comment (sverps) [inline packages/nextjs/components/scaffold-eth/FaucetButton.tsx:47]: See my other coment abbout `isMounted`. I don't think it's doing anything here.

**Review by sverps — CHANGES_REQUESTED** [review]
Nice cleanup @rin-st 

Added two small comments

File: packages/nextjs/components/scaffold-eth/Faucet.tsx (hunk 1 above)
Comment (rin-st) [reply packages/nextjs/components/scaffold-eth/Faucet.tsx:80]: `isMounted` is `false` by default and becomes `true` in `useEffect` after the first render. I added it because it fixes hydration error - `useNetwork` works differently for nextjs server and client

Comment (carletex) [reply packages/nextjs/components/scaffold-eth/Faucet.tsx:80]: Yeah! I think it's because of NextJS pre-rendering. the `isMounted` logic makes that pre-rendering === first render. If not, we'd get a Hydration error.

**Comment by technophile-04** [comment]
Also one thing I think now is we can have only maybe as `burnerWallet`  boolean instead of having it as an object and maybe rename it to `burnerWalletOnlyLocal`?    

we will be just needing to update it here : 
https://github.com/scaffold-eth/scaffold-eth-2/blob/50de54f54db133b5a06ae41f3f9d610127925843/packages/nextjs/services/web3/wagmiConnectors.tsx#L64

and update this : 
https://github.com/scaffold-eth/scaffold-eth-2/blob/50de54f54db133b5a06ae41f3f9d610127925843/packages/nextjs/services/web3/wagmi-burner/burnerWalletConfig.ts#L29


We have burnerWallet always on `hardhat` and disabled by default in other chains and if user makes that boolean true it will show on other chains too

File: packages/nextjs/components/scaffold-eth/Faucet.tsx (hunk 1 above)
Comment (sverps) [reply packages/nextjs/components/scaffold-eth/Faucet.tsx:80]: Aaah of course, should have realized in the context of this fix, you're right @rin-st

**Comment by rin-st** [comment]
updated. We should mention changes on https://github.com/scaffold-eth/scaffold-eth-2/pull/384 after merge

**Review by sverps — APPROVED** [review]
Looks good

**Review by technophile-04 — APPROVED** [review]
Tysm @rin-st 🙌 It works nicely!!
