### PR TITLE
use next-themes for handling theme

### LINKED ISSUE #709: dangerouslySetInnerHtml error in browser console when refreshing page in dark mode.
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Which method was used to setup Scaffold-ETH 2 ?

npx create-eth@latest

### Example Repo
https://github.com/Hotmanics/dangerously-set-inner-html-example

### Current Behavior

On loading a scaffold eth project, with dark mode enabled, in the web browser, it results in this error:

Screenshot 2024-02-07 at 5 14 30 PM

`Warning: Prop `dangerouslySetInnerHTML` did not match. Server: "[data-rk]{--rk-blurs-modalOverlay:blur(0px);--rk-fonts-body:SFRounded, ui-rounded, \"SF Pro Rounded\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\";--rk-radii-actionButton:9999px;--rk-radii-connectButton:12px;--rk-radii-menuButton:12px;--rk-radii-modal:24px;--rk-radii-modalMobile:28px;--rk-colors-accentColor:#0E76FD;--rk-colors-accentColorForeground:#FFF;--rk-colors-actionButtonBorder:rgba(0, 0, 0, 0.04);--rk-colors-actionButtonBorderMobile:rgba(0, 0, 0, 0.06);--rk-colors-actionButtonSecondaryBackground:rgba(0, 0, 0, 0.06);--rk-colors-closeButton:rgba(60, 66, 66, 0.8);--rk-colors-closeButtonBackground:rgba(0, 0, 0, 0.06);--rk-colors-connectButtonBackground:#FFF;--rk-colors-connectButtonBackgroundError:#FF494A;--rk-colors-connectButtonInnerBackground:linear-gradient(0deg, rgba(0, 0, 0, 0.03), rgba(0, 0, 0, 0.06));--rk-colors-connectButtonText:#25292E;--rk-colors-connectButtonTextError:#FFF;--rk-colors-connectionIndicator:#30E000;--rk-colors-downloadBottomCardBackground:linear-gradient(126deg, rgba(255, 255, 255, 0) 9.49%, rgba(171, 171, 171, 0.04) 71.04%), #FFFFFF;--rk-colors-downloadTopCardBackground:linear-gradient(126deg, rgba(171, 171, 171, 0.2) 9.49%, rgba(255, 255, 255, 0) 71.04%), #FFFFFF;--rk-colors-error:#FF494A;--rk-colors-generalBorder:rgba(0, 0, 0, 0.06);--rk-colors-generalBorderDim:rgba(0, 0, 0, 0.03);--rk-colors-menuItemBackground:rgba(60, 66, 66, 0.1);--rk-colors-modalBackdrop:rgba(0, 0, 0, 0.3);--rk-colors-modalBackground:#FFF;--rk-colors-modalBorder:transparent;--rk-colors-modalText:#25292E;--rk-colors-modalTextDim:rgba(60, 66, 66, 0.3);--rk-colors-modalTextSecondary:rgba(60, 66, 66, 0.6);--rk-colors-profileAction:#FFF;--rk-colors-profileActionHover:rgba(255, 255, 255, 0.5);--rk-colors-profileForeground:rgba(60, 66, 66, 0.06);--rk-colors-selectedOptionBorder:rgba(60, 66, 66, 0.1);--rk-colors-standby:#FFD641;--rk-shadows-connectButton:0px 4px 12px rgba(0, 0, 0, 0.1);--rk-shadows-dialog:0px 8px 32px rgba(0, 0, 0, 0.32);--rk-shadows-profileDetailsAction:0px 2px 6px rgba(37, 41, 46, 0.04);--rk-shadows-selectedOption:0px 2px 6px rgba(0, 0, 0, 0.24);--rk-shadows-selectedWallet:0px 2px 6px rgba(0, 0, 0, 0.12);--rk-shadows-walletLogo:0px 2px 16px rgba(0, 0, 0, 0.16);}" Client: "[data-rk]{--rk-blurs-modalOverlay:blur(0px);--rk-fonts-body:SFRounded, ui-rounded, \"SF Pro Rounded\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\";--rk-radii-actionButton:9999px;--rk-radii-connectButton:12px;--rk-radii-menuButton:12px;--rk-radii-modal:24px;--rk-radii-modalMobile:28px;--rk-colors-accentColor:#3898FF;--rk-colors-accentColorForeground:#FFF;--rk-colors-actionButtonBorder:rgba(255, 255, 255, 0.04);--rk-colors-actionButtonBorderMobile:rgba(255, 255, 255, 0.08);--rk-colors-actionButtonSecondaryBackground:rgba(255, 255, 255, 0.08);--rk-colors-closeButton:rgba(224, 232, 255, 0.6);--rk-colors-closeButtonBackground:rgba(255, 255, 255, 0.08);--rk-colors-connectButtonBackground:#1A1B1F;--rk-colors-connectButtonBackgroundError:#FF494A;--rk-colors-connectButtonInnerBackground:linear-gradient(0deg, rgba(255, 255, 255, 0.075), rgba(255, 255, 255, 0.15));--rk-colors-connectButtonText:#FFF;--rk-colors-connectButtonTextError:#FFF;--rk-colors-connectionIndicator:#30E000;--rk-colors-downloadBottomCardBackground:linear-gradient(126deg, rgba(0, 0, 0, 0) 9.49%, rgba(120, 120, 120, 0.2) 71.04%), #1A1B1F;--rk-colors-downloadTopCardBackground:linear-gradient(126deg, rgba(120, 120, 120, 0.2) 9.49%, rgba(0, 0, 0, 0) 71.04%), #1A1B1F;--rk-colors-error:#FF494A;--rk-colors-generalBorder:rgba(255, 255, 255, 0.08);--rk-colors-generalBorderDim:rgba(255, 255, 255, 0.04);--rk-colors-menuItemBackground:rgba(224, 232, 255, 0.1);--rk-colors-modalBackdrop:rgba(0, 0, 0, 0.5);--rk-colors-modalBackground:#1A1B1F;--rk-colors-modalBorder:rgba(255, 255, 255, 0.08);--rk-colors-modalText:#FFF;--rk-colors-modalTextDim:rgba(224, 232, 255, 0.3);--rk-colors-modalTextSecondary:rgba(255, 255, 255, 0.6);--rk-colors-profileAction:rgba(224, 232, 255, 0.1);--rk-colors-profileActionHover:rgba(224, 232, 255, 0.2);--rk-colors-profileForeground:rgba(224, 232, 255, 0.05);--rk-colors-selectedOptionBorder:rgba(224, 232, 255, 0.1);--rk-colors-standby:#FFD641;--rk-shadows-connectButton:0px 4px 12px rgba(0, 0, 0, 0.1);--rk-shadows-dialog:0px 8px 32px rgba(0, 0, 0, 0.32);--rk-shadows-profileDetailsAction:0px 2px 6px rgba(37, 41, 46, 0.04);--rk-shadows-selectedOption:0px 2px 6px rgba(0, 0, 0, 0.24);--rk-shadows-selectedWallet:0px 2px 6px rgba(0, 0, 0, 0.24);--rk-shadows-walletLogo:0px 2px 16px rgba(0, 0, 0, 0.16);}"
`

### Expected Behavior

No error to occur.

### Steps To Reproduce

1. Run `npx create-eth@latest`, set the project name to anything, set solidity framework to `foundry`, `Y` to install packages.  Finish creating the project.
2.  Cd into project folder and run `yarn start`.
3. Access `localhost:3000` in a web browser (Brave & Chrome tested) WITH and WITHOUT wallet extensions enabled.
4. Toggle dark mode ON.
5. Refresh the page.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by technophile-04**
## Description

Background #707, This works nicely and also fixes the flickering issue. 

[`next-themes`](https://www.npmjs.com/package/next-themes) seems like an popular library and used by [ShadCn](https://ui.shadcn.com/docs/dark-mode/next) and [NextUI](https://nextui.org/docs/customization/dark-mode)

This also fixes #709 

Test App : https://usehooks-ts-test.vercel.app/

the only downside is currently it does not hot react to theme changes of system preference (at the OS level). Although can be easily handled if we give the user an extra  choice "System" instead of only 2 : 
Screenshot 2024-02-09 at 7 40 51 PM

PS: It defaults to user's OS theme when user very first time visit the website, after that if he switches the theme manually then it doesn't react to OS changes

### CODE REVIEW

File: packages/nextjs/app/layout.tsx [hunk 1]
```diff
@@ -43,9 +44,11 @@ export const metadata: Metadata = {
 
 const ScaffoldEthApp = ({ children }: { children: React.ReactNode }) => {
   return (
-    <html>
+    <html suppressHydrationWarning>
```
Comment (technophile-04) [inline packages/nextjs/app/layout.tsx:47]: > This property only applies one level deep, so it won't block hydration warnings on other elements.

~ [next-themes docs](https://github.com/pacocoursey/next-themes?tab=readme-ov-file#with-app)

File: packages/nextjs/components/ScaffoldEthAppWithProviders.tsx [hunk 2]
```diff
@@ -37,15 +37,21 @@ const ScaffoldEthApp = ({ children }: { children: React.ReactNode }) => {
...
+  }, []);
 
   return (
     <WagmiConfig config={wagmiConfig}>
       <ProgressBar />
       <RainbowKitProvider
         chains={appChains.chains}
         avatar={BlockieAvatar}
-        theme={isDarkMode ? darkTheme() : lightTheme()}
+        theme={mounted ? (isDarkMode ? darkTheme() : lightTheme()) : lightTheme()}
```
Comment (technophile-04) [inline packages/nextjs/components/ScaffoldEthAppWithProviders.tsx:54]: Had to do this because of #709

File: packages/nextjs/tailwind.config.js [hunk 3]
```diff
@@ -2,12 +2,12 @@
...
   content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}", "./utils/**/*.{js,ts,jsx,tsx}"],
   plugins: [require("daisyui")],
-  darkTheme: "scaffoldEthDark",
+  darkTheme: "dark",
   // DaisyUI theme colors
   daisyui: {
     themes: [
       {
-        scaffoldEth: {
+        light: {
```
Comment (technophile-04) [inline packages/nextjs/tailwind.config.js:10]: Had to change the name because of https://github.com/pacocoursey/next-themes/issues/167#issuecomment-1935981004

**Review by Pabl0cks — APPROVED** [review]
Really nice job @technophile-04 exploring this option! 🙌

It's working great to me in both Dark and Light OS 👌

I had a super small issue in your deployed example, where the day/night radio button was moving a few pixels above the initial render when doing F5. In localhost it was working fine, and when I deployed to Vercel it was working fine too. Not big deal anyways, was only happening when forcing the refresh, not when changing tabs.

**Comment by technophile-04** [comment]
> I had a super small issue in your deployed example, where the day/night radio button was moving a few pixels above the initial render when doing F5.

Ohh yeah, actually saw it was not happening on localhost more importantly on `chains.hardhat` because we have Faucet button and BlockExplorer buttons present always there, when I deployed to vercel I switched to `sepolia` because of which the ETH price button was popping up a bit late which was causing `SwitchTheme`  to change its height 


https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/4fb5f366-6132-4fd2-b4d1-1ec9c88549ac

But fixed at https://github.com/scaffold-eth/scaffold-eth-2/pull/712/commits/677cd37e04e22f06d98dd7fc7904e360f7df0a69 by giving it some definite height so that it doesn't change 

Thanks Pablo 🙌

**Comment by Pabl0cks** [comment]
> Ohh yeah, actually saw it was not happening on localhost more importantly on chains.hardhat because we have Faucet button and BlockExplorer buttons present always there, when I deployed to vercel I switched to sepolia because of which the ETH price button was popping up a bit late which was causing SwitchTheme to change its height

Nice catch and fix!

**Review by rin-st — APPROVED** [review]

**Comment by rin-st** [comment]
completely agree with you here https://github.com/scaffold-eth/scaffold-eth-2/pull/707#issuecomment-1936046060
> At the beginning, I thought it's not worth using the whole library just to handle the theme but digging a bit deep in the NextJS context I think its worth using due to all the caveats present, and handling them ourselves properly might be a pain.

tested it and works great for me
great job as always!
