### PR TITLE
Fix contract interactions error

### LINKED ISSUE #1145: Non-readable errors for contract-to-contract interactions
Started [here](https://github.com/scaffold-eth/se-2-challenges/issues/315)

How to reproduce:
<details><summary>ContractA</summary>
<p>

```
//SPDX-License-Identifier: MIT
pragma solidity >=0.8.0 <0.9.0;

import "hardhat/console.sol";
import "./ContractB.sol";

/**
 * Contract A that calls Contract B's getError function
 * @author BuidlGuidl
 */
contract ContractA {
    ContractB public contractB;

    constructor(address _contractBAddress) {
        contractB = ContractB(_contractBAddress);
    }

    /**
     * Function that executes ContractB's getError function
     * This will propagate the B_error() from ContractB
     */
    function getErrorFromB() public {
        console.log("ContractA: About to call ContractB.getError()");
        contractB.getError();
    }
} 

```

</p>
</details> 

<details><summary>ContractB</summary>
<p>

```
//SPDX-License-Identifier: MIT
pragma solidity >=0.8.0 <0.9.0;

import "hardhat/console.sol";

/**
 * Contract B that contains a function that emits an error
 * @author BuidlGuidl
 */
contract ContractB {
    // Custom error definition
    error B_error();

    /**
     * Function that emits a random error B_error()
     */
    function getError() public pure {
        console.log("ContractB: About to emit B_error()");
        revert B_error();
    }
} 
```

</p>
</details> 

<details><summary>01_deploy_contracts_ab.ts</summary>
<p>

```
import { HardhatRuntimeEnvironment } from "hardhat/types";
import { DeployFunction } from "hardhat-deploy/types";
import { Contract } from "ethers";

/**
 * Deploys ContractB and ContractA
 * ContractB is deployed first, then ContractA is deployed with ContractB's address
 *
 * @param hre HardhatRuntimeEnvironment object.
 */
const deployContractsAB: DeployFunction = async function (hre: HardhatRuntimeEnvironment) {
  const { deployer } = await hre.getNamedAccounts();
  const { deploy } = hre.deployments;

  // Deploy ContractB first
  await deploy("ContractB", {
    from: deployer,
    args: [], // ContractB has no constructor arguments
    log: true,
    autoMine: true,
  });

  // Get the deployed ContractB to get its address
  const contractB = await hre.ethers.getContract<Contract>("ContractB", deployer);
  console.log("📦 ContractB deployed at:", await contractB.getAddress());

  // Deploy ContractA with ContractB's address
  await deploy("ContractA", {
    from: deployer,
    args: [await contractB.getAddress()], // Pass ContractB's address to ContractA constructor
    log: true,
    autoMine: true,
  });

  // Get the deployed ContractA
  const contractA = await hre.ethers.getContract<Contract>("ContractA", deployer);
  console.log("📦 ContractA deployed at:", await contractA.getAddress());
  console.log("🔗 ContractA is connected to ContractB at:", await contractA.contractB());
};

export default deployContractsAB;

// Tags are useful if you have multiple deploy files and only want to run one of them.
// e.g. yarn deploy --tags ContractsAB
deployContractsAB.tags = ["ContractsAB"];

```

</p>
</details> 

<details><summary>page.tsx</summary>
<p>

```
"use client";

import { useState } from "react";
import Link from "next/link";
import type { NextPage } from "next";
import { useAccount } from "wagmi";
import { BugAntIcon, MagnifyingGlassIcon } from "@heroicons/react/24/outline";
import { Address } from "~~/components/scaffold-eth";
import { useScaffoldWriteContract } from "~~/hooks/scaffold-eth";

const Home: NextPage = () => {
  const { address: connectedAddress } = useAccount();
  const [isLoading, setIsLoading] = useState(false);

  const { writeContractAsync: writeContractAAsync } = useScaffoldWriteContract({
    contractName: "ContractA",
  });

  const handleCallContractA = async () => {
    setIsLoading(true);

    try {
      // Call the getErrorFromB function which will throw an error
      await writeContractAAsync({
        functionName: "getErrorFromB",
      });
    } catch (error: any) {
      console.log(error);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <>
      <div className="flex items-center flex-col grow pt-10">
        <div className="px-5">
          <h1 className="text-center">
            <span className="block text-2xl mb-2">Welcome to</span>
            <span className="block text-4xl font-bold">Scaffold-ETH 2</span>
          </h1>
          <div className="flex justify-center items-center space-x-2 flex-col">
            <p className="my-2 font-medium">Connected Address:</p>
            <Address address={connectedAddress} />
          </div>

          {/* ContractA Button Section */}
          <div className="flex flex-col items-center mt-8 p-6 bg-base-200 rounded-lg">
            <h2 className="text-xl font-bold mb-4">ContractA Function Call</h2>
            <button
              className={`btn btn-primary ${isLoading ? "loading" : ""}`}
              onClick={handleCallContractA}
              disabled={isLoading}
            >
              {isLoading ? "Calling..." : "Call getErrorFromB()"}
            </button>
          </div>

          <p className="text-center text-lg mt-6">
            Get started by editing{" "}
            <code className="italic bg-base-300 text-base font-bold max-w-full break-words break-all inline-block">
              packages/nextjs/app/page.tsx
            </code>
          </p>
          <p className="text-center text-lg">
            Edit your smart contract{" "}
            <code className="italic bg-base-300 text-base font-bold max-w-full break-words break-all inline-block">
              YourContract.sol
            </code>{" "}
            in{" "}
            <code className="italic bg-base-300 text-base font-bold max-w-full break-words break-all inline-block">
              packages/hardhat/contracts
            </code>
          </p>
        </div>

        <div className="grow bg-base-300 w-full mt-16 px-8 py-12">
          <div className="flex justify-center items-center gap-12 flex-col md:flex-row">
            <div className="flex flex-col bg-base-100 px-10 py-10 text-center items-center max-w-xs rounded-3xl">
              <BugAntIcon className="h-8 w-8 fill-secondary" />
              <p>
                Tinker with your smart contract using the{" "}
                <Link href="/debug" passHref className="link">
                  Debug Contracts
                </Link>{" "}
                tab.
              </p>
            </div>
            <div className="flex flex-col bg-base-100 px-10 py-10 text-center items-center max-w-xs rounded-3xl">
              <MagnifyingGlassIcon className="h-8 w-8 fill-secondary" />
              <p>
                Explore your local transactions with the{" "}
                <Link href="/blockexplorer" passHref className="link">
                  Block Explorer
                </Link>{" "}
                tab.
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
```

</p>
</details> 

- yarn chain, yarn deploy, yarn start
- click `getErrorFromB()` button from `page.tsx`. You'll get the error

Image

### PR DESCRIPTION
**Pull request by rin-st**
See the bug and how to reproduce in #1145 

It can't parse the error because it checks only abi of the ContractA. This PR fixes it, now when trying to find error it parses abi's of all the deployed contracts.

Error after fix
image

Fixes #1145

### CODE REVIEW

**Review by Pabl0cks — APPROVED** [review]
Tested with token vendor challenge, trying to sell more tokens than current user balance, and it's working nicely to me.

Before vs After:

image

**Review by technophile-04 — COMMENTED** [review]
Thanks @rin-st and Pablo for testing!! Looks nice to me! Just added a small comment 🙌 

Ohh also update if you do `yarn next:check-types` without any contract deployment you get: 

image

File: packages/nextjs/utils/scaffold-eth/contract.ts [hunk 1]
```diff
@@ -335,6 +337,68 @@ export type UseScaffoldEventHistoryData<
...
+ */
+const getParsedErrorWithAllAbis = (error: any, chainId: AllowedChainIds): string => {
+  const originalParsedError = getParsedError(error);
+
+  // Check if this is an unrecognized error signature
+  if (originalParsedError.includes("Encoded error signature") && originalParsedError.includes("not found on ABI")) {
+    const signatureMatch = originalParsedError.match(/0x[a-fA-F0-9]{8}/);
+    const signature = signatureMatch ? signatureMatch[0] : "";
+
+    if (signature) {
```
Comment (technophile-04) [inline packages/nextjs/utils/scaffold-eth/contract.ts:352]: Maybe we could early returns instead of nested if blocks 

if (!signature) return originalParsedError;

File: packages/nextjs/utils/scaffold-eth/contract.ts [hunk 2]
```diff
@@ -335,6 +337,68 @@ export type UseScaffoldEventHistoryData<
...
+      try {
+        // Get all deployed contracts for the current chain
+        const chainContracts = deployedContractsData[chainId];
+        if (chainContracts) {
```
Comment (technophile-04) [inline packages/nextjs/utils/scaffold-eth/contract.ts:356]: Same here early return: 

`if (!chainContracts) return;`

File: packages/nextjs/utils/scaffold-eth/contract.ts [hunk 3]
```diff
@@ -345,7 +409,9 @@ export const simulateContractWriteAndNotifyError = async ({
   try {
     await simulateContract(wagmiConfig, params);
   } catch (error) {
-    const parsedError = getParsedError(error);
+    const chainId = wagmiConfig.chains[0]?.id as AllowedChainIds;
```
[the remark this answers is not in the document]
Comment (rin-st) [reply packages/nextjs/utils/scaffold-eth/contract.ts]: [4a16ecd](https://github.com/scaffold-eth/scaffold-eth-2/pull/1146/commits/4a16ecdc13c3199aec90dbd5ef26db2e3fa711a5) Updated, thank you!

File: packages/nextjs/utils/scaffold-eth/contract.ts (hunk 2 above)
Comment (rin-st) [reply packages/nextjs/utils/scaffold-eth/contract.ts]: [9f2e17e](https://github.com/scaffold-eth/scaffold-eth-2/pull/1146/commits/9f2e17e35e9e7de24d9ce4687c800642b3b6078d)

File: packages/nextjs/utils/scaffold-eth/contract.ts (hunk 1 above)
Comment (rin-st) [reply packages/nextjs/utils/scaffold-eth/contract.ts]: [9f2e17e](https://github.com/scaffold-eth/scaffold-eth-2/pull/1146/commits/9f2e17e35e9e7de24d9ce4687c800642b3b6078d)

**Comment by rin-st** [comment]
Thanks for reviews, guys!

> Ohh also update if you do yarn next:check-types without any contract deployment you get:

Fixed! [33fa96f](https://github.com/scaffold-eth/scaffold-eth-2/pull/1146/commits/33fa96fb4564e0459a0cb0aaf8af6481c83856fe)

---

One more note: if we disable simulate
```
const { writeContractAsync: writeContractAAsync } = useScaffoldWriteContract({
    contractName: "ContractA",
    disableSimulate: true,
  })
```
we're getting the same error as before.

So I updated `useTransactor` a bit so it also parses all the abi's [38fd747](https://github.com/scaffold-eth/scaffold-eth-2/pull/1146/commits/38fd7477247c286bf80320ddedb4c69366cf8be0)

**Comment by technophile-04** [comment]
Tysm Rinat!! Looks great! Just pushed a small commit, instead of using hardcode hardaht chainId used the scaffoldConfig's 0th network in `useTransactor` since contract on 0th chainId is assumed to be on all chains. I mean this case is not going to happen more likely because walletClient with give `chainId` but just incase 🙌

**Comment by damianmarti** [comment]
This is great @rin-st!! Nice improvement!
