### PR TITLE
fix local next build

### LINKED ISSUE #748: bug: cd packages/nextjs && yarn run build doesn't work
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Which method was used to setup Scaffold-ETH 2 ?

npx create-eth@latest

### Current Behavior

Unable to run `cd packages/nextjs && yarn run build`.

### Expected Behavior

Build completes correctly.

### Steps To Reproduce

```sh
node@a5a3444e3b03:/mnt$ npx create-eth@latest

 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 | Create Scaffold-ETH 2 app |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+

? Your project name: my-dapp-example
? What solidity framework do you want to use? hardhat
? Install packages? Yes


  ✔ 📁 Create project directory /mnt/my-dapp-example
  ✔ 🚀 Creating a new Scaffold-ETH 2 app in my-dapp-example
  ✔ 📦 Installing dependencies with yarn, this could take a while
  ✔ 📡 Initializing Git repository 

  

  Congratulations! Your project has been scaffolded! 🎉

  Next steps:
  
  cd my-dapp-example
  
    	Start the local development node
    	yarn chain
    
    	In a new terminal window, deploy your contracts
    	yarn deploy
   
  	In a new terminal window, start the frontend
  	yarn start
  
  Thanks for using Scaffold-ETH 2 🙏, Happy Building!
  
node@a5a3444e3b03:/mnt$ cd my-dapp-example/
node@a5a3444e3b03:/mnt/my-dapp-example$ yarn install
➤ YN0065: Yarn will periodically gather anonymous telemetry: https://yarnpkg.com/advanced/telemetry
➤ YN0065: Run yarn config set --home enableTelemetry 0 to disable

➤ YN0000: ┌ Resolution step
➤ YN0002: │ @se-2/hardhat@workspace:packages/hardhat doesn't provide @ethersproject/bytes (p65fdc), requested by @typechain/ethers-v5
➤ YN0002: │ @se-2/hardhat@workspace:packages/hardhat doesn't provide @types/node (p7e794), requested by ts-node
➤ YN0060: │ @se-2/hardhat@workspace:packages/hardhat provides eslint (pd27d9) with version 8.26.0, which doesn't satisfy what @typescript-eslint/eslint-plugin and some of its descendants request
➤ YN0060: │ @se-2/hardhat@workspace:packages/hardhat provides eslint (p4c933) with version 8.26.0, which doesn't satisfy what @typescript-eslint/parser requests
➤ YN0060: │ @se-2/hardhat@workspace:packages/hardhat provides ethers (p48e1c) with version 6.10.0, which doesn't satisfy what @typechain/ethers-v5 requests
➤ YN0060: │ @se-2/hardhat@workspace:packages/hardhat provides typechain (p3e0db) with version 8.1.1, which doesn't satisfy what @typechain/ethers-v6 requests
➤ YN0060: │ @se-2/hardhat@workspace:packages/hardhat provides typechain (p47737) with version 8.1.1, which doesn't satisfy what @typechain/hardhat requests
➤ YN0002: │ @se-2/nextjs@workspace:packages/nextjs doesn't provide @typescript-eslint/parser (p1319a), requested by @typescript-eslint/eslint-plugin
➤ YN0002: │ daisyui@npm:4.5.0 doesn't provide postcss (p2dbb8), requested by postcss-js
➤ YN0002: │ react-hot-toast@npm:2.4.1 [ef549] doesn't provide csstype (p8c5a0), requested by goober
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 385ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 847ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 787ms
➤ YN0000: Done with warnings in 2s 258ms
node@a5a3444e3b03:/mnt/my-dapp-example$ yarn run build
Usage Error: Couldn't find a script named "build".

$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
node@a5a3444e3b03:/mnt/my-dapp-example$ cd packages/nextjs/
node@a5a3444e3b03:/mnt/my-dapp-example/packages/nextjs$ yarn run build
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

   ▲ Next.js 14.0.4


🌼   daisyUI 4.5.0
├─ ✔︎ 2 themes added             https://daisyui.com/docs/themes
╰─ ★ Star daisyUI on GitHub     https://github.com/saadeghi/daisyui

 ✓ Creating an optimized production build    
 ✓ Compiled successfully

./app/blockexplorer/address/[address]/page.tsx
1:1  Warning: Delete `⏎`  prettier/prettier
86:28  Warning: Insert `⏎`  prettier/prettier

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
 ✓ Linting and checking validity of types    
   Collecting page data  ...TypeError: Invalid URL
    at new URL (node:internal/url:787:36)
    at 47436 (/mnt/my-dapp-example/packages/nextjs/.next/server/chunks/739.js:29:928)
    at Function.t (/mnt/my-dapp-example/packages/nextjs/.next/server/webpack-runtime.js:1:143)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async collectGenerateParams (/mnt/my-dapp-example/packages/nextjs/node_modules/next/dist/build/utils.js:884:17)
    at async /mnt/my-dapp-example/packages/nextjs/node_modules/next/dist/build/utils.js:1100:17
    at async Span.traceAsyncFn (/mnt/my-dapp-example/packages/nextjs/node_modules/next/dist/trace/trace.js:147:20) {
  code: 'ERR_INVALID_URL',
  input: 'http://localhost:undefined'
}

> Build error occurred
Error: Failed to collect page data for /blockexplorer/address/[address]
    at /mnt/my-dapp-example/packages/nextjs/node_modules/next/dist/build/utils.js:1220:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
   Collecting page data  .
node@a5a3444e3b03:/mnt/my-dapp-example/packages/nextjs$
```

### Anything else?

Running from a container launched like this `docker run --rm -it -v"$PWD":/mnt -u$UID:$(id -g) -p3001:3000 -p8546:8545 node bash -i` and then running:
```sh
node@a5a3444e3b03:/mnt$ git config --global user.email "you@example.com"
node@a5a3444e3b03:/mnt$ git config --global user.name "Your Name"
```

### PR DESCRIPTION
**Pull request by technophile-04**
## Description

If you `cd packages/nextjs` and run `yarn build` it fails, 

The reason was `baseUrl` which we were generating for metadata. 

This PR adds a fallback port, similar to how next [`metadataBase`  default](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#default-value) works. 

Btw we need `baseUrl` since OpenGraph.image and Twitter.image they both absoulte path and passing just `/thumbnail.jpg` does not work, check out code [commet here](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#opengraph). 

Closes #748

### CODE REVIEW

File: packages/nextjs/app/layout.tsx [hunk 1]
```diff
@@ -4,9 +4,9 @@ import { ScaffoldEthAppWithProviders } from "~~/components/ScaffoldEthAppWithPro
 import { ThemeProvider } from "~~/components/ThemeProvider";
 import "~~/styles/globals.css";
 
-const baseUrl = process.env.NEXT_PUBLIC_VERCEL_URL
```
Comment (technophile-04) [inline packages/nextjs/app/layout.tsx:7]: using `VERCEL_URL` instead of `NEXT_PUBLIC_VERCEL_URL` to just follow convention what default [`metadataBase`](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#default-value) is following. 

Both [`VERCEL_URL`](https://vercel.com/docs/concepts/projects/environment-variables/system-environment-variables#:~:text=.-,VERCEL_URL,-The%20domain%20name) and [`NEXT_PUBLIC_VERCEL_URL`](https://vercel.com/docs/projects/environment-variables/system-environment-variables#framework-environment-variables) are prefilled by vercel so both works 🙌

**Review by Pabl0cks — APPROVED** [review]
Great job @technophile-04!! `yarn run build` is working again on my Windows environment after your fix 🙌

TYSM

**Review by rin-st — APPROVED** [review]
lgtm!
